{"timestamp": "2024-04-22 08:42:08.199400", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\createPatients_controller.py\", line 65, in create_patient_gomedisys\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400\n"}}
{"timestamp": "2024-04-22 08:43:37.247688", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\createPatients_controller.py\", line 66, in create_patient_gomedisys\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400\n"}}
{"timestamp": "2024-04-22 09:12:16.764268", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '415 Unsupported Media Type' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\createPatients_controller.py\", line 66, in create_patient_gomedisys\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '415 Unsupported Media Type' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415\n"}}
{"timestamp": "2024-04-22 09:13:42.858718", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '415 Unsupported Media Type' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\createPatients_controller.py\", line 66, in create_patient_gomedisys\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '415 Unsupported Media Type' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415\n"}}
{"timestamp": "2024-04-22 09:14:25.488107", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\createPatients_controller.py\", line 66, in create_patient_gomedisys\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400\n"}}
{"timestamp": "2024-04-22 09:15:59.288120", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\createPatients_controller.py\", line 66, in create_patient_gomedisys\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400\n"}}
{"timestamp": "2024-04-22 09:26:38.969502", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\createPatients_controller.py\", line 66, in create_patient_gomedisys\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400\n"}}
{"timestamp": "2024-04-22 09:27:02.221648", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\createPatients_controller.py\", line 66, in create_patient_gomedisys\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400\n"}}
{"timestamp": "2024-04-22 09:28:20.207750", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\createPatients_controller.py\", line 66, in create_patient_gomedisys\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400\n"}}
{"timestamp": "2024-04-22 09:28:55.006562", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\createPatients_controller.py\", line 66, in create_patient_gomedisys\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400\n"}}
{"timestamp": "2024-04-22 09:30:15.830182", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\createPatients_controller.py\", line 66, in create_patient_gomedisys\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400\n"}}
{"timestamp": "2024-04-22 09:32:34.459550", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\createPatients_controller.py\", line 66, in create_patient_gomedisys\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400\n"}}
{"timestamp": "2024-04-22 09:33:51.493348", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\createPatients_controller.py\", line 66, in create_patient_gomedisys\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400\n"}}
{"timestamp": "2024-04-22 09:35:21.106988", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\createPatients_controller.py\", line 66, in create_patient_gomedisys\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400\n"}}
{"timestamp": "2024-04-22 09:36:47.839207", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\createPatients_controller.py\", line 66, in create_patient_gomedisys\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400\n"}}
{"timestamp": "2024-04-22 09:37:38.358681", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\createPatients_controller.py\", line 66, in create_patient_gomedisys\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400\n"}}
{"timestamp": "2024-04-22 09:40:47.245633", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\createPatients_controller.py\", line 66, in create_patient_gomedisys\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400\n"}}
{"timestamp": "2024-04-22 09:41:26.664562", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\createPatients_controller.py\", line 66, in create_patient_gomedisys\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400\n"}}
{"timestamp": "2024-04-22 09:41:48.736241", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\createPatients_controller.py\", line 66, in create_patient_gomedisys\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/CreatePatient'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400\n"}}
{"timestamp": "2024-05-16 16:37:53.579929", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '405 Method Not Allowed' for url 'https://servicesrest.gomedisys.com/api/Appointment/GetPatientInfo'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 43, in get_patient_info\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '405 Method Not Allowed' for url 'https://servicesrest.gomedisys.com/api/Appointment/GetPatientInfo'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405\n"}}
{"timestamp": "2024-05-16 16:41:25.951352", "traceback_details": {"exception_type": "JSONDecodeError", "exception_message": "Expecting value: line 1 column 1 (char 0)", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 43, in get_patient_info\n    print(response.json())\n          ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 762, in json\n    return jsonlib.loads(self.content, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n"}}
{"timestamp": "2024-05-16 16:45:21.960443", "traceback_details": {"exception_type": "JSONDecodeError", "exception_message": "Expecting value: line 1 column 1 (char 0)", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 43, in get_patient_info\n    print(response.json())\n          ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 762, in json\n    return jsonlib.loads(self.content, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n"}}
{"timestamp": "2024-05-16 16:52:17.893443", "traceback_details": {"exception_type": "JSONDecodeError", "exception_message": "Expecting value: line 1 column 1 (char 0)", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 43, in get_patient_info\n    print(response.json())\n          ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 762, in json\n    return jsonlib.loads(self.content, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n"}}
{"timestamp": "2024-05-16 16:53:31.832920", "traceback_details": {"exception_type": "JSONDecodeError", "exception_message": "Expecting value: line 1 column 1 (char 0)", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 44, in get_patient_info\n    print(response.json())\n          ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 762, in json\n    return jsonlib.loads(self.content, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n"}}
{"timestamp": "2024-05-16 16:54:33.467040", "traceback_details": {"exception_type": "JSONDecodeError", "exception_message": "Expecting value: line 1 column 1 (char 0)", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 44, in get_patient_info\n    print(response.json())\n          ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 762, in json\n    return jsonlib.loads(self.content, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n"}}
{"timestamp": "2024-05-16 16:55:46.435169", "traceback_details": {"exception_type": "JSONDecodeError", "exception_message": "Expecting value: line 1 column 1 (char 0)", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 44, in get_patient_info\n    print(response.json())\n          ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 762, in json\n    return jsonlib.loads(self.content, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n"}}
{"timestamp": "2024-05-17 09:25:25.142406", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '415 Unsupported Media Type' for url 'https://servicesrest.gomedisys.com/api/Appointment/GetPatientInfo?keyWS=DCEE6AC0-B97D-4F50-8D31-7EE863EEBBCA&idDocumentType=CC&documentNumber=1234'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 46, in get_patient_info\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '415 Unsupported Media Type' for url 'https://servicesrest.gomedisys.com/api/Appointment/GetPatientInfo?keyWS=DCEE6AC0-B97D-4F50-8D31-7EE863EEBBCA&idDocumentType=CC&documentNumber=1234'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415\n"}}
{"timestamp": "2024-05-17 09:27:04.083104", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '415 Unsupported Media Type' for url 'https://servicesrest.gomedisys.com/api/Appointment/GetPatientInfo?keyWS=DCEE6AC0-B97D-4F50-8D31-7EE863EEBBCA&idDocumentType=CC&documentNumber=1234'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 46, in get_patient_info\n    response = await client.post(URL, json=data_patient, headers=headers)\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '415 Unsupported Media Type' for url 'https://servicesrest.gomedisys.com/api/Appointment/GetPatientInfo?keyWS=DCEE6AC0-B97D-4F50-8D31-7EE863EEBBCA&idDocumentType=CC&documentNumber=1234'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415\n"}}
{"timestamp": "2024-05-17 09:28:07.600993", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '405 Method Not Allowed' for url 'https://servicesrest.gomedisys.com/api/Appointment/GetPatientInfo'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 49, in get_patient_info\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '405 Method Not Allowed' for url 'https://servicesrest.gomedisys.com/api/Appointment/GetPatientInfo'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405\n"}}
{"timestamp": "2024-05-17 09:31:02.654302", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '415 Unsupported Media Type' for url 'https://servicesrest.gomedisys.com/api/Appointment/GetPatientInfo?keyWS=DCEE6AC0-B97D-4F50-8D31-7EE863EEBBCA&typeDocument=CC&documentNumber=1234'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 46, in get_patient_info\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '415 Unsupported Media Type' for url 'https://servicesrest.gomedisys.com/api/Appointment/GetPatientInfo?keyWS=DCEE6AC0-B97D-4F50-8D31-7EE863EEBBCA&typeDocument=CC&documentNumber=1234'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415\n"}}
{"timestamp": "2024-05-17 09:37:59.863410", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '415 Unsupported Media Type' for url 'https://servicesrest.gomedisys.com/api/Appointment/GetPatientInfo?keyWS=DCEE6AC0-B97D-4F50-8D31-7EE863EEBBCA&typeDocument=CC&documentNumber=1234'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 46, in get_patient_info\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '415 Unsupported Media Type' for url 'https://servicesrest.gomedisys.com/api/Appointment/GetPatientInfo?keyWS=DCEE6AC0-B97D-4F50-8D31-7EE863EEBBCA&typeDocument=CC&documentNumber=1234'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415\n"}}
{"timestamp": "2024-05-17 09:41:13.545971", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '404 Not Found' for url 'https://servicesrest.gomedisys.com/api/api/Appointment/GetPatientInfo?keyWS=DCEE6AC0-B97D-4F50-8D31-7EE863EEBBCA&typeDocument=CC&documentNumber=1234'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 46, in get_patient_info\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '404 Not Found' for url 'https://servicesrest.gomedisys.com/api/api/Appointment/GetPatientInfo?keyWS=DCEE6AC0-B97D-4F50-8D31-7EE863EEBBCA&typeDocument=CC&documentNumber=1234'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404\n"}}
{"timestamp": "2024-05-17 09:42:56.247548", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '404 Not Found' for url 'https://servicesrest.gomedisys.com/api/api/Appointment/GetPatientInfo?keyWS=DCEE6AC0-B97D-4F50-8D31-7EE863EEBBCA&typeDocument=CC&documentNumber=1234'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 46, in get_patient_info\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '404 Not Found' for url 'https://servicesrest.gomedisys.com/api/api/Appointment/GetPatientInfo?keyWS=DCEE6AC0-B97D-4F50-8D31-7EE863EEBBCA&typeDocument=CC&documentNumber=1234'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404\n"}}
{"timestamp": "2024-05-17 09:43:42.176817", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '415 Unsupported Media Type' for url 'https://servicesrest.gomedisys.com/api/Appointment/GetPatientInfo?keyWS=DCEE6AC0-B97D-4F50-8D31-7EE863EEBBCA&typeDocument=CC&documentNumber=1234'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 46, in get_patient_info\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '415 Unsupported Media Type' for url 'https://servicesrest.gomedisys.com/api/Appointment/GetPatientInfo?keyWS=DCEE6AC0-B97D-4F50-8D31-7EE863EEBBCA&typeDocument=CC&documentNumber=1234'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415\n"}}
{"timestamp": "2024-05-17 09:44:03.975919", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '415 Unsupported Media Type' for url 'https://servicesrest.gomedisys.com/api/Appointment/GetPatientInfo?keyWS=B12B1BD0-7B54-4E28-9152-9275116C1635&typeDocument=CC&documentNumber=1234'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 46, in get_patient_info\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '415 Unsupported Media Type' for url 'https://servicesrest.gomedisys.com/api/Appointment/GetPatientInfo?keyWS=B12B1BD0-7B54-4E28-9152-9275116C1635&typeDocument=CC&documentNumber=1234'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415\n"}}
{"timestamp": "2024-05-17 09:51:47.298352", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '404 Not Found' for url 'https://servicesrest.gomedisys.com/api/api/Appointment/GetPatientInfo'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 49, in get_patient_info\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '404 Not Found' for url 'https://servicesrest.gomedisys.com/api/api/Appointment/GetPatientInfo'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404\n"}}
{"timestamp": "2024-05-17 09:53:22.057861", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '404 Not Found' for url 'https://servicesrest.gomedisys.com/api/api/Appointment/GetPatientInfo'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 50, in get_patient_info\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '404 Not Found' for url 'https://servicesrest.gomedisys.com/api/api/Appointment/GetPatientInfo'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404\n"}}
{"timestamp": "2024-05-17 09:54:30.920982", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/GetPatientInfo'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 50, in get_patient_info\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/GetPatientInfo'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400\n"}}
{"timestamp": "2024-05-17 10:02:28.165625", "traceback_details": {"exception_type": "UnsupportedProtocol", "exception_message": "Request URL is missing an 'http://' or 'https://' protocol.", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 67, in map_httpcore_exceptions\n    yield\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 371, in handle_async_request\n    resp = await self._pool.handle_async_request(req)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 215, in handle_async_request\n    raise UnsupportedProtocol(\nhttpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 157, in get_patient_info\n    response = await client.request(\"GET\", URL, content=data_json, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_client.py\", line 1559, in request\n    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_client.py\", line 1646, in send\n    response = await self._send_handling_auth(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_client.py\", line 1674, in _send_handling_auth\n    response = await self._send_handling_redirects(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_client.py\", line 1711, in _send_handling_redirects\n    response = await self._send_single_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_client.py\", line 1748, in _send_single_request\n    response = await transport.handle_async_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 370, in handle_async_request\n    with map_httpcore_exceptions():\n  File \"C:\\Users\\SebastianAndresSuare\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\contextlib.py\", line 158, in __exit__\n    self.gen.throw(value)\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 84, in map_httpcore_exceptions\n    raise mapped_exc(message) from exc\nhttpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.\n"}}
{"timestamp": "2024-05-17 10:03:24.434597", "traceback_details": {"exception_type": "UnsupportedProtocol", "exception_message": "Request URL is missing an 'http://' or 'https://' protocol.", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 67, in map_httpcore_exceptions\n    yield\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 371, in handle_async_request\n    resp = await self._pool.handle_async_request(req)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 215, in handle_async_request\n    raise UnsupportedProtocol(\nhttpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 157, in get_patient_info\n    response = await client.request(\"GET\", URL, content=data_json, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_client.py\", line 1559, in request\n    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_client.py\", line 1646, in send\n    response = await self._send_handling_auth(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_client.py\", line 1674, in _send_handling_auth\n    response = await self._send_handling_redirects(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_client.py\", line 1711, in _send_handling_redirects\n    response = await self._send_single_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_client.py\", line 1748, in _send_single_request\n    response = await transport.handle_async_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 370, in handle_async_request\n    with map_httpcore_exceptions():\n  File \"C:\\Users\\SebastianAndresSuare\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\contextlib.py\", line 158, in __exit__\n    self.gen.throw(value)\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 84, in map_httpcore_exceptions\n    raise mapped_exc(message) from exc\nhttpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.\n"}}
{"timestamp": "2024-05-17 10:03:47.720447", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/GetPatientInfo'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 160, in get_patient_info\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/GetPatientInfo'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400\n"}}
{"timestamp": "2024-05-17 10:07:21.120883", "traceback_details": {"exception_type": "HTTPStatusError", "exception_message": "Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/GetPatientInfo'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 161, in get_patient_info\n    response.raise_for_status()\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_models.py\", line 759, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://servicesrest.gomedisys.com/api/Appointment/GetPatientInfo'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400\n"}}
{"timestamp": "2024-05-17 10:09:12.110394", "traceback_details": {"exception_type": "UnsupportedProtocol", "exception_message": "Request URL is missing an 'http://' or 'https://' protocol.", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 67, in map_httpcore_exceptions\n    yield\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 371, in handle_async_request\n    resp = await self._pool.handle_async_request(req)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 215, in handle_async_request\n    raise UnsupportedProtocol(\nhttpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 158, in get_patient_info\n    response = await client.request(\"GET\", URL, content=data_json, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_client.py\", line 1559, in request\n    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_client.py\", line 1646, in send\n    response = await self._send_handling_auth(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_client.py\", line 1674, in _send_handling_auth\n    response = await self._send_handling_redirects(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_client.py\", line 1711, in _send_handling_redirects\n    response = await self._send_single_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_client.py\", line 1748, in _send_single_request\n    response = await transport.handle_async_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 370, in handle_async_request\n    with map_httpcore_exceptions():\n  File \"C:\\Users\\SebastianAndresSuare\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\contextlib.py\", line 158, in __exit__\n    self.gen.throw(value)\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\CargueMasivoGomedisys\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 84, in map_httpcore_exceptions\n    raise mapped_exc(message) from exc\nhttpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.\n"}}
{"timestamp": "2024-05-17 10:33:05.532169", "traceback_details": "Traceback (most recent call last):\n  File \"C:\\Users\\SebastianAndresSuare\\OneDrive - CLINICOS PROGRAMAS DE ATENCION INTEGRAL SAS IPS\\Documentos\\CargueMasivoGomedisys\\app\\CreacionMasivaPacientes\\controllers\\validatePatients_controller.py\", line 44, in get_patient_info\n    response = await client.get(\n                     ^^^^^^^^^^^\nTypeError: AsyncClient.get() got an unexpected keyword argument 'json'\n"}
